// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqSi1zITR6noPOhzJaQGq24SY5le5FYU',
    appId: '1:247571720095:web:c0d496c034e49ee895bfaa',
    messagingSenderId: '247571720095',
    projectId: 'inventi-fc7cc',
    authDomain: 'inventi-fc7cc.firebaseapp.com',
    databaseURL: 'https://inventi-fc7cc-default-rtdb.firebaseio.com',
    storageBucket: 'inventi-fc7cc.firebasestorage.app',
    measurementId: 'G-Z6VY1BNX0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZBrDrwoxUL2pSlnYvmWpB4SlFLaZn49w',
    appId: '1:247571720095:android:1fa108253582d61a95bfaa',
    messagingSenderId: '247571720095',
    projectId: 'inventi-fc7cc',
    databaseURL: 'https://inventi-fc7cc-default-rtdb.firebaseio.com',
    storageBucket: 'inventi-fc7cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR3aDwF8fTX6vUMxVRlrlcWBitRvooye4',
    appId: '1:247571720095:ios:add5bd6e13738f1795bfaa',
    messagingSenderId: '247571720095',
    projectId: 'inventi-fc7cc',
    databaseURL: 'https://inventi-fc7cc-default-rtdb.firebaseio.com',
    storageBucket: 'inventi-fc7cc.firebasestorage.app',
    iosBundleId: 'com.example.inventi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR3aDwF8fTX6vUMxVRlrlcWBitRvooye4',
    appId: '1:247571720095:ios:add5bd6e13738f1795bfaa',
    messagingSenderId: '247571720095',
    projectId: 'inventi-fc7cc',
    databaseURL: 'https://inventi-fc7cc-default-rtdb.firebaseio.com',
    storageBucket: 'inventi-fc7cc.firebasestorage.app',
    iosBundleId: 'com.example.inventi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqSi1zITR6noPOhzJaQGq24SY5le5FYU',
    appId: '1:247571720095:web:9b684d0503d5a84095bfaa',
    messagingSenderId: '247571720095',
    projectId: 'inventi-fc7cc',
    authDomain: 'inventi-fc7cc.firebaseapp.com',
    databaseURL: 'https://inventi-fc7cc-default-rtdb.firebaseio.com',
    storageBucket: 'inventi-fc7cc.firebasestorage.app',
    measurementId: 'G-FCWD0H28DM',
  );
}
